// Loader for the WASM engine bundle produced by `pnpm build:wasm`.
// The bundle directory `src/lib/engine-wasm/` is gitignored — generated by
// wasm-pack from `crates/core` with the `wasm` feature. Run `pnpm build:wasm`
// once after pulling, or rely on the CI step that runs it before tauri build.

import init, { WasmEngine } from "./engine-wasm/smoothscroll_core";
import wasmUrl from "./engine-wasm/smoothscroll_core_bg.wasm?url";

let initialized: Promise<void> | null = null;

export async function ensureWasmReady(): Promise<void> {
  if (!initialized) initialized = init(wasmUrl).then(() => undefined);
  return initialized;
}

export async function createEngine(settingsJson: string): Promise<WasmEngine> {
  await ensureWasmReady();
  return new WasmEngine(settingsJson);
}

export type { WasmEngine };
