//! `CGEventTap` for scrollWheel events on a dedicated `CFRunLoop` thread.
//!
//! Modifier keys are read directly from the event flags (no separate sampler
//! thread needed, unlike Windows).

#![cfg(target_os = "macos")]

use crate::traits::{HookDecision, HookEventSink, HookHandle, MouseHook};
use crate::types::{ModifierKeys, PlatformError, Result};
use core_foundation::base::TCFType;
use core_foundation::mach_port::CFMachPort;
use core_foundation::runloop::{kCFRunLoopCommonModes, CFRunLoop, CFRunLoopSource};
use core_graphics::event::{
    CGEvent, CGEventFlags, CGEventTap, CGEventTapLocation, CGEventTapOptions, CGEventTapPlacement,
    CGEventType,
};
use parking_lot::Mutex;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::thread;

pub struct MacosMouseHook;

impl MacosMouseHook {
    pub fn new() -> Self {
        Self
    }
}

impl Default for MacosMouseHook {
    fn default() -> Self {
        Self::new()
    }
}

impl MouseHook for MacosMouseHook {
    fn install(&self, sink: Arc<dyn HookEventSink>) -> Result<HookHandle> {
        if !crate::macos::permissions::is_trusted(false) {
            return Err(PlatformError::PermissionDenied);
        }

        let alive = Arc::new(AtomicBool::new(true));
        let stop_runloop = Arc::new(Mutex::new(None::<CFRunLoop>));

        let alive_thread = alive.clone();
        let stop_runloop_thread = stop_runloop.clone();
        let sink_for_thread = sink.clone();
        let join = thread::Builder::new()
            .name("ss-mouse-hook".into())
            .spawn(move || run_loop_thread(sink_for_thread, alive_thread, stop_runloop_thread))
            .map_err(|e| PlatformError::Os(format!("spawn hook thread: {e}")))?;

        struct Installed {
            alive: Arc<AtomicBool>,
            runloop: Arc<Mutex<Option<CFRunLoop>>>,
            join: Option<thread::JoinHandle<()>>,
        }
        impl Drop for Installed {
            fn drop(&mut self) {
                self.alive.store(false, Ordering::SeqCst);
                if let Some(rl) = self.runloop.lock().take() {
                    rl.stop();
                }
                if let Some(h) = self.join.take() {
                    let _ = h.join();
                }
            }
        }

        Ok(HookHandle {
            _inner: Box::new(Installed {
                alive,
                runloop: stop_runloop,
                join: Some(join),
            }),
        })
    }
}

fn run_loop_thread(
    sink: Arc<dyn HookEventSink>,
    alive: Arc<AtomicBool>,
    stop_runloop: Arc<Mutex<Option<CFRunLoop>>>,
) {
    let sink_for_cb = sink.clone();
    let tap = match CGEventTap::new(
        CGEventTapLocation::HID,
        CGEventTapPlacement::HeadInsertEventTap,
        CGEventTapOptions::Default,
        vec![CGEventType::ScrollWheel],
        move |_proxy, _ty, event| handle_event(&sink_for_cb, event),
    ) {
        Ok(t) => t,
        Err(_) => return,
    };

    let source = unsafe {
        CFRunLoopSource::wrap_under_get_rule(tap.mach_port().create_runloop_source(0).unwrap())
    };
    let runloop = CFRunLoop::get_current();
    runloop.add_source(&source, unsafe { kCFRunLoopCommonModes });
    tap.enable();

    *stop_runloop.lock() = Some(runloop.clone());

    while alive.load(Ordering::SeqCst) {
        CFRunLoop::run_in_mode(
            unsafe { kCFRunLoopCommonModes },
            std::time::Duration::from_millis(100),
            true,
        );
    }
}

fn handle_event<'a>(sink: &Arc<dyn HookEventSink>, event: &mut CGEvent) -> Option<&'a CGEvent> {
    // Skip events we ourselves generated by checking the event source state.
    // (CGEvent doesn't have an LLMHF_INJECTED equivalent; we tag with an event
    //  source userData but for v1 we accept the small risk and rely on the OS
    //  not delivering our HID-posted events back to us in practice.)

    let mods = read_modifiers(event);

    // Vertical axis 1, horizontal axis 2 (raw double — needs scaling to "delta").
    // macOS scroll deltas tend to be ±1..±10 per click;
    // multiply by WHEEL_DELTA(120) so the engine math (delta / WHEEL_DELTA = notches)
    // matches Windows.
    use core_graphics::event::CGEventField::{
        ScrollWheelEventDeltaAxis1, ScrollWheelEventDeltaAxis2,
    };
    let v_axis = event.get_integer_value_field(ScrollWheelEventDeltaAxis1) as i32;
    let h_axis = event.get_integer_value_field(ScrollWheelEventDeltaAxis2) as i32;

    // Map "lines" → delta units.
    let v_delta = v_axis * 120;
    let h_delta = h_axis * 120;

    // Decide which axis dominates this event. macOS sends scrollWheel events
    // with both axes set when a Magic Mouse moves diagonally — handle both.
    let mut swallow = false;
    if v_delta != 0 {
        if matches!(sink.on_wheel(v_delta, mods), HookDecision::Swallow) {
            swallow = true;
        }
    }
    if h_delta != 0 {
        if matches!(sink.on_hwheel(h_delta), HookDecision::Swallow) {
            swallow = true;
        }
    }

    if swallow {
        None
    } else {
        Some(event)
    }
}

fn read_modifiers(event: &CGEvent) -> ModifierKeys {
    let flags = event.get_flags();
    ModifierKeys {
        shift: flags.contains(CGEventFlags::CGEventFlagShift),
        ctrl: flags.contains(CGEventFlags::CGEventFlagControl),
        alt: flags.contains(CGEventFlags::CGEventFlagAlternate),
    }
}
