import { expect, test } from '@playwright/test'
import { getDictionarySync, type Locale } from '../lib/i18n/dict'

const localePages = [
  { path: '/', lang: 'en', ogLocale: 'en_US', text: 'Smooth scrolling for Windows,', answer: 'SmoothScroll is free smooth-scrolling software for Windows 10 and 11.', locale: 'en' as Locale },
  { path: '/vi/', lang: 'vi', ogLocale: 'vi_VN', text: 'Cuộn mượt cho Windows', answer: 'SmoothScroll là phần mềm cuộn mượt miễn phí cho Windows 10 và 11.', locale: 'vi' as Locale },
  { path: '/zh/', lang: 'zh-Hans', ogLocale: 'zh_CN', text: 'Windows 平滑滚动', answer: 'SmoothScroll 是适用于 Windows 10 和 11 的免费平滑滚动软件。', locale: 'zh' as Locale },
  { path: '/how-it-works/', lang: 'en', ogLocale: 'en_US', text: 'See how SmoothScroll', locale: 'en' as Locale },
  { path: '/vi/how-it-works/', lang: 'vi', ogLocale: 'vi_VN', text: 'Xem cách SmoothScroll', locale: 'vi' as Locale },
  { path: '/zh/how-it-works/', lang: 'zh-Hans', ogLocale: 'zh_CN', text: '看 SmoothScroll', locale: 'zh' as Locale },
] as const

const canonicalCases = [
  ['/', 'https://smoothscroll.top/'],
  ['/vi/', 'https://smoothscroll.top/vi/'],
  ['/zh/', 'https://smoothscroll.top/zh/'],
  ['/how-it-works/', 'https://smoothscroll.top/how-it-works/'],
  ['/vi/how-it-works/', 'https://smoothscroll.top/vi/how-it-works/'],
  ['/zh/how-it-works/', 'https://smoothscroll.top/zh/how-it-works/'],
] as const

for (const page of localePages) {
  test(`${page.path} serves localized raw HTML`, async ({ request }) => {
    const response = await request.get(page.path)
    const html = await response.text()

    await expect(response).toBeOK()
    expect(html).toContain(`<html lang="${page.lang}"`)
    expect(html).toContain(`property="og:locale" content="${page.ogLocale}"`)
    expect(html).toContain(page.text)
  })
}

for (const [path, canonical] of canonicalCases) {
  test(`${path} has self-canonical and reciprocal hreflang`, async ({ request }) => {
    const html = await (await request.get(path)).text()

    expect(html).toContain(`rel="canonical" href="${canonical}"`)
    expect(html).toMatch(/hrefLang="en"|hreflang="en"/)
    expect(html).toMatch(/hrefLang="vi"|hreflang="vi"/)
    expect(html).toMatch(/hrefLang="zh-Hans"|hreflang="zh-Hans"/)
    expect(html).toMatch(/hrefLang="x-default"|hreflang="x-default"/)
  })
}

test('homepage publishes complete social preview metadata', async ({ request }) => {
  const html = await (await request.get('/')).text()

  expect(html).toContain('<title>Smooth Scrolling Software for Windows | SmoothScroll</title>')
  expect(html).toContain('name="description" content="SmoothScroll is free smooth scrolling software for Windows 10 and 11.')
  expect(html).toContain('property="og:title"')
  expect(html).toContain('property="og:description"')
  expect(html).toContain('property="og:url" content="https://smoothscroll.top/"')
  expect(html).toContain('property="og:image" content="https://smoothscroll.top/assets/og-image.png"')
  expect(html).toContain('property="og:image:width" content="1200"')
  expect(html).toContain('property="og:image:height" content="630"')
  expect(html).toContain('name="twitter:card" content="summary_large_image"')
  expect(html).not.toContain('Generated by Next.js')
})

test('localized homepage graphs match their page language and visible FAQ', async ({ request }) => {
  for (const page of localePages.slice(0, 3)) {
    const html = await (await request.get(page.path)).text()
    const match = html.match(/<script type="application\/ld\+json">(.*?)<\/script>/)

    expect(match).not.toBeNull()
    const json = JSON.parse(match![1])
    const graph = json['@graph'] as {
      '@type': string
      url?: string
      inLanguage?: string
      mainEntity?: unknown[]
      isAccessibleForFree?: boolean
      downloadUrl?: string
      featureList?: string[]
    }[]
    const types = graph.map((item) => item['@type'])
    const webPage = graph.find((item) => item['@type'] === 'WebPage')
    const webSite = graph.find((item) => item['@type'] === 'WebSite')
    const software = graph.find((item) => item['@type'] === 'SoftwareApplication')
    const faq = graph.find((item) => item['@type'] === 'FAQPage')

    expect(types).toEqual(expect.arrayContaining(['Organization', 'WebSite', 'WebPage', 'SoftwareApplication', 'FAQPage']))
    expect(webPage).toMatchObject({ url: `https://smoothscroll.top${page.path}`, inLanguage: page.lang })
    expect(webSite).toMatchObject({ inLanguage: page.lang })
    expect(software).toMatchObject({
      isAccessibleForFree: true,
      downloadUrl: 'https://github.com/quangtruong2003/SmoothScroll/releases/latest',
    })
    const expectedFeature = getDictionarySync(page.locale).features?.items?.[0]?.title
    expect(software?.featureList).toContain(expectedFeature)
    // Structured answers only earn rich results when the same text is server-rendered.
    const dictionary = getDictionarySync(page.locale)
    const renderedQuestions = (dictionary.faq?.questions ?? []).filter(({ q, a }) => q && a)

    expect(faq?.mainEntity).toHaveLength(renderedQuestions.length + 1)
    for (const { a } of renderedQuestions) {
      expect(html).toContain(a!.slice(0, 40).replace(/&/g, '&amp;'))
    }
  }
})

test('collapsed FAQ answers stay hidden for readers but present for crawlers', async ({ page }) => {
  await page.goto('/')

  const firstAnswer = page.locator('[role="region"][data-state="closed"]').first()

  await expect(firstAnswer).not.toBeVisible()
  await expect(firstAnswer).not.toBeEmpty()
})

test('localized guide graphs publish breadcrumbs and preserve page language', async ({ request }) => {
  for (const page of localePages.slice(3)) {
    const html = await (await request.get(page.path)).text()
    const match = html.match(/<script type="application\/ld\+json">(.*?)<\/script>/)
    const graph = JSON.parse(match![1])['@graph'] as {
      '@type': string
      url?: string
      inLanguage?: string
      itemListElement?: { item: string }[]
    }[]
    const types = graph.map((item) => item['@type'])
    const webPage = graph.find((item) => item['@type'] === 'WebPage')
    const breadcrumb = graph.find((item) => item['@type'] === 'BreadcrumbList')
    const homePath = page.path.replace('how-it-works/', '')

    expect(types).not.toContain('FAQPage')
    expect(types).toContain('BreadcrumbList')
    expect(webPage).toMatchObject({ url: `https://smoothscroll.top${page.path}`, inLanguage: page.lang })
    expect(breadcrumb?.itemListElement?.map(({ item }) => item)).toEqual([
      `https://smoothscroll.top${homePath}`,
      `https://smoothscroll.top${page.path}`,
    ])
  }
})

test('localized home pages publish visible citable answers', async ({ request }) => {
  for (const page of localePages.slice(0, 3)) {
    const html = await (await request.get(page.path)).text()
    if (!('answer' in page)) throw new Error(`Missing answer fixture for ${page.path}`)
    expect(html).toContain(page.answer)
    expect(html).toContain('https://github.com/quangtruong2003/SmoothScroll')
    expect(html).toContain('/how-it-works/')
    expect(html).toContain('2026-08-12')
    expect(html).toContain(getDictionarySync(page.locale).install?.supportNotice)
    expect(html).toMatch(/maintained by|duy trì bởi|由.*维护/i)
  }
})

test('raw home HTML exposes locale links and page evidence', async ({ request }) => {
  const html = await (await request.get('/')).text()
  const match = html.match(/<script type="application\/ld\+json">(.*?)<\/script>/)
  const json = JSON.parse(match![1])
  const webPage = json['@graph'].find((item: { '@type': string }) => item['@type'] === 'WebPage')

  expect(html).toMatch(/href="\/vi\/?"/)
  expect(html).toMatch(/href="\/zh\/?"/)
  expect(webPage.author).toEqual({ '@id': 'https://smoothscroll.top/#organization' })
  expect(webPage.dateModified).toBe('2026-08-12')
})

test('sitemap lists every localized canonical page', async ({ request }) => {
  const xml = await (await request.get('/sitemap.xml')).text()
  for (const url of canonicalCases.map(([, url]) => url)) {
    expect(xml).toContain(`<loc>${url}</loc>`)
  }
  expect(xml).toContain('<lastmod>2026-08-12</lastmod>')
  expect(xml).not.toContain('marquee-debug')
})

test('publishes optional AI discovery document', async ({ request }) => {
  const response = await request.get('/llms.txt')
  const text = await response.text()

  await expect(response).toBeOK()
  expect(text).toContain('# SmoothScroll')
  expect(text).toContain('https://smoothscroll.top/how-it-works/')
  expect(text).toContain('https://github.com/quangtruong2003/SmoothScroll')
})

test('keeps debug route out of search indexes', async ({ request }) => {
  const html = await (await request.get('/marquee-debug/')).text()
  expect(html).toMatch(/noindex/i)
})
